name: pushenAufAzureRepo

on:
  push:
    branches:
      - main  # Passe diesen Branch-Namen an, falls nötig

jobs:
  copy-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "JonasPollokZweitag"
        git config --global user.email "jonas.pollok@zweitag.de"

    - name: Get the last commit
      id: last_commit
      run: echo "::set-output name=commit::$(git rev-parse HEAD)"

    - name: Force push to Azure DevOps
      env:
        AZURE_REPO_URL: https://waiv@dev.azure.com/waiv/waiv/_git/Jonas-Open-Tester.git
        AZURE_PAT: ${{ secrets.AZURE_PAT }}  # Stelle sicher, dass du ein Personal Access Token (PAT) als Secret in deinem GitHub-Repository hinzufügst
      run: |
        git remote add azure https://waiv:${{ secrets.AZURE_PAT }}@dev.azure.com/waiv/waiv/_git/Jonas-Open-Tester.git
        git push azure ${{ steps.last_commit.outputs.commit }}:refs/heads/main --force
