name: pushenAufAzureRepo

on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  reinitialize-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Remove .git directory
      run: |
        rm -rf .git
    - name: Reinitialize Git repository
      run: |
        git init
        git config --global user.name "JonasPollokZweitag"
        git config --global user.email "jonas.pollok@zweitag.de"
        git add .
        git commit -m "Reinitialize repository"
    - name: push repository
      env:
        AZURE_REPO_URL: https://waiv@dev.azure.com/waiv/waiv/_git/Jonas-Open-Tester.git
        AZURE_PAT: ${{ secrets.AZURE_PAT }}
      run: |
        git push --mirror https://${{ secrets.AZURE_PAT }}@dev.azure.com/waiv/waiv/_git/Jonas-Open-Tester.git
