name: pushenAufAzureRepo

on:
  #schedule:
  #  - cron: "*/5 * * * *" # alle 5 min
  #  - cron: "* 11 * * 5" # jeden Freitag um 13 Uhr (11 Uhr UTC)
 
  
jobs:
  reinitialize-repo-with-pipeline-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Remove .git directory
      run: |
        rm -rf .git

    - name: Create azure-pipelines.yml
      run: |
        echo "trigger:" > azure-pipelines.yml
        echo "- master" >> azure-pipelines.yml
        echo "" >> azure-pipelines.yml
        echo "pool:" >> azure-pipelines.yml
        echo "  vmImage: ubuntu-latest" >> azure-pipelines.yml
        echo "" >> azure-pipelines.yml
        echo "steps:" >> azure-pipelines.yml
        echo "" >> azure-pipelines.yml
        echo "- task: AdvancedSecurity-Codeql-Init@1" >> azure-pipelines.yml
        echo "  inputs:" >> azure-pipelines.yml
        echo "    languages: 'python'" >> azure-pipelines.yml
        echo "" >> azure-pipelines.yml
        echo "- task: AdvancedSecurity-Dependency-Scanning@1" >> azure-pipelines.yml
        echo "" >> azure-pipelines.yml
        echo "- task: AdvancedSecurity-Codeql-Analyze@1" >> azure-pipelines.yml
  
    - name: Reinitialize Git repository
      run: |
        git init
        git config --global user.name "JonasPollokZweitag"
        git config --global user.email "jonas.pollok@zweitag.de"
        git add .
        git commit -m "Reinitialize repository"
    - name: push repository
      env:
        AZURE_REPO_URL: https://waiv@dev.azure.com/waiv/waiv/_git/Jonas-Open-Tester.git
        AZURE_PAT: ${{ secrets.AZURE_PAT }}
      run: |
        git push --mirror https://${{ secrets.AZURE_PAT }}@dev.azure.com/Zweitag/waiv/_git/Import-Test
